improve pipex test

diff --git a/pipex/Makefile b/pipex/Makefile
--- a/pipex/Makefile
+++ b/pipex/Makefile
@@ -43,7 +43,7 @@ define MEMCHECK
 		cat mem_check; \
 		echo ; \
 	else \
-		printf " ✅${GREEN}${BOLD}Valgrind ${RESET}(exit $$exit_code) "; \
+		printf " ✅${GREEN}${BOLD}Valgrind ${RESET}"; \
 	fi;
 	@if command -v funcheck > /dev/null 2>&1; then \
 		rm -f ./mem_check && printf "$(3)" | funcheck -a ./pipex $(2) > mem_check 2>&1; \
@@ -65,14 +65,8 @@ define MEMCHECK_SIMPLE
 		cat mem_check; \
 		echo ; \
 	else \
-		printf " ✅${GREEN}${BOLD}Valgrind ${RESET}(exit $$exit_code) "; \
+		printf " ✅${GREEN}${BOLD}Valgrind ${RESET}"; \
 	fi;
-	@if command -v funcheck > /dev/null 2>&1; then \
-		rm -f ./mem_check && printf "$(3)" | funcheck ./pipex $(2) > mem_check 2>&1; \
-		grep -q -E "failed|not freed|invalid" mem_check && (printf "${BG_RED}${BOLD} Funcheck ${RESET}\n" && cat mem_check && echo) || printf " ✅${GREEN}${BOLD}Funcheck ${RESET}" ; \
-	else \
-		printf "${BG_RED}${BOLD} Funcheck not installed ${RESET}\n"; \
-	fi; \
 	rm -f mem_check
 endef
 
@@ -85,43 +79,46 @@ define RUNTEST
 		limiter=$$2; shift 2; \
 		while [ $$# -gt 1 ]; do cmds="$$cmds | $$1"; shift; done; \
 		outfile=$$1; \
+		outfile_bash=$$outfile"_bash"; \
 		cmds=$${cmds# | }; \
-		printf "$(3)" | timeout 5 ./pipex $(2) > ./pipex_out 2>./pipex_err; \
+		printf "$(3)" | timeout 5 ./pipex $(2) 2>./pipex_err; \
 		exit_pipex=$$?; \
-		printf "$(3)" | timeout 5 bash -c "$$cmds >> $$outfile" > ./bash_out 2>./bash_err; \
+		printf "$(3)" | timeout 5 bash -c "$$cmds >> $$outfile_bash" 2>./bash_err; \
 		exit_bash=$$?; \
 	else \
 		infile=$$1; shift; \
 		while [ $$# -gt 1 ]; do cmds="$$cmds | $$1"; shift; done; \
 		outfile=$$1; \
-		printf "$(3)" | timeout 5 ./pipex $(2) > ./pipex_out 2>./pipex_err; \
+		outfile_bash=$$outfile"_bash"; \
+		printf "$(3)" | timeout -k 5 ./pipex $(2) 2>./pipex_err; \
 		exit_pipex=$$?; \
-		printf "$(3)" | timeout 5 bash -c "< $$infile $$cmds > $$outfile" > ./bash_out 2>./bash_err; \
+		printf "$(3)" | timeout -k 5 bash -c "< $$infile $$cmds > $$outfile_bash" 2>./bash_err; \
 		exit_bash=$$?; \
 	fi; \
 	if [ $$exit_pipex -ne $$exit_bash ]; then \
 		printf "${BG_RED}${BOLD} Exit mismatch (pipex=$$exit_pipex, bash=$$exit_bash) ${RESET}"; \
 	else \
-		if diff -q ./pipex_out ./bash_out >/dev/null 2>&1; then \
+		if diff -q ./$$outfile ./$$outfile_bash >/dev/null 2>&1; then \
 			printf " ✅${GREEN}${BOLD} OK ${RESET}"; \
 		else \
 			printf "${BG_RED}${BOLD} Output mismatch ${RESET}\n"; \
-			diff -u ./bash_out ./pipex_out || true; \
+			diff -u ./$$outfile ./$$outfile_bash || true; \
 		fi; \
 	fi; \
-	$(call MEMCHECK_SIMPLE,$(1), $(2), $(3));
- 	rm -f ./pipex_out ./bash_out ./pipex_err ./bash_err
+	$(call MEMCHECK_SIMPLE,$(1), $(2), $(3)); \
+ 	rm -f ./pipex_out ./bash_out ./pipex_err ./bash_err $$outfile_bash $$outfile
 endef
 
-prepare:
+prepare: clean_tests
 	@echo -e "hello\nworld\npipex" > input
 	@touch empty
 	@echo "secret data" > secret && chmod 000 secret
 	@touch out_noperm && chmod 000 out_noperm
+	@touch out_noperm_bash && chmod 000 out_noperm
 	@yes "pipex test line" | head -n 10000 > bigfile
 
 clean_tests:
-	@rm -f input empty secret out_noperm bigfile output nofile
+	@rm -f input empty secret out_noperm bigfile output nofile mem_check pipex
 	@chmod 644 secret out_noperm 2>/dev/null || true
 
 # ============================================================================= #
@@ -131,12 +128,18 @@ clean_tests:
 ## test : test current exo
 .PHONY: test
 test: prepare
-	@clear
-	@make -C ../../pipex -s pipex
+	@printf "\n\n${SUBTITLE}----------------> Bonus <----------------${RESET}\n"
+	@make -qp -C ../../pipex | grep -q bonus: || (printf "${BG_RED}${BOLD} No bonus ${RESET}\n" && make clean_tests && exit 1)
+	@printf "\n${SUBTITLE}Checking make command${RESET}\n"
+	@printf "bonus:" && make -s -C ../../pipex bonus && printf "${GREEN}${BOLD} OK ${RESET}\n" || printf "${BG_RED}${BOLD} FAILED ${RESET}\n"
+	@printf "No relink:" && make -C ../../pipex bonus | grep -q "Nothing to be done for 'bonus'" && printf "${GREEN}${BOLD} OK ${RESET}\n" || printf "${BG_RED}${BOLD} FAILED ${RESET}\n"
 	@mv ../../pipex/pipex ./pipex
-	@printf "\n\n${SUBTITLE}Checking leaks and malloc protections${RESET}"
-	@$(call RUNTEST,"1.Basic","input" "cat" "wc -l" "output")
-	@echo
+	@printf "\n\n${SUBTITLE}Tests${RESET}"
+	@$(call RUNTEST,"B5.Here_doc basic","here_doc" "END" "cat" "wc -l" "output_hd",hello\nworld\npipex\nEND\n)
+	@$(call RUNTEST,"B6.Here_doc print input","here_doc" "END" "cat" "wc -l" "output_hd",hello\nworld\npipex\nEND\n)
+	@$(call RUNTEST,"B6.Here_doc empty input","here_doc" "END" "cat" "wc -c" "output_hd",END\n)
+	@$(call RUNTEST,"B7.Here_doc multiple cmds","here_doc" "FINISH" "tr a-z A-Z" "grep PIPEX" "wc -l" "output_hd",foo\npipex\nbar\nFINISH\n)
+	@$(call RUNTEST,"B8.Here_doc invalid command","here_doc" "END" "cat" "doesnotexist" "wc -c" "output_hd",hello\nworld\npipex\nEND\n)
 	@make clean_tests
 
 .PHONY: pipex
@@ -162,10 +165,10 @@ pipex: prepare
 		fi; \
 	fi
 	@printf "\n\n${SUBTITLE}Checking make command${RESET}\n"
-	@printf "pipex:" && make -C ../../pipex -s pipex && printf "${GREEN}${BOLD} OK ${RESET}\n" || printf "${BG_RED}${BOLD} FAILED ${RESET}\n"
+	@printf "pipex:" && make -C ../../pipex -s && printf "${GREEN}${BOLD} OK ${RESET}\n" || printf "${BG_RED}${BOLD} FAILED ${RESET}\n"
 	@printf "No relink:" && make -C ../../pipex | grep -q 'is up to date' && printf "${GREEN}${BOLD} OK ${RESET}\n" || printf "${BG_RED}${BOLD} FAILED ${RESET}\n"
 	@mv ../../pipex/pipex ./pipex && make -C ../../pipex -s fclean
-	@printf "\n\n${SUBTITLE}Testing${RESET}"
+	@printf "\n\n${SUBTITLE}Tests${RESET}"
 	@$(call RUNTEST,"0.Empty input") 
 	@$(call RUNTEST,"1.Basic","input" "cat" "wc -l" "output")
 	@$(call RUNTEST,"2.Basic","input" "ls -la" "grep pipex" "output")
@@ -183,8 +186,21 @@ pipex: prepare
 	@$(call RUNTEST,"14.Same infile and outfile","input" "cat" "wc -l" "input")
 	@$(call RUNTEST,"15.Command with quotes","input" "echo 'hello world'" "wc -w" "output")
 	@$(call RUNTEST,"16.Chain grep","input" "grep hello" "grep pipex" "output")
+	@printf "\n\n${SUBTITLE}----------------> Bonus <----------------${RESET}\n"
+	@make -qp -C ../../pipex | grep -q bonus: || (printf "${BG_RED}${BOLD} No bonus ${RESET}\n" && make clean_tests && exit 1)
+	@printf "\n${SUBTITLE}Checking make command${RESET}\n"
+	@printf "bonus:" && make -s -C ../../pipex bonus && printf "${GREEN}${BOLD} OK ${RESET}\n" || printf "${BG_RED}${BOLD} FAILED ${RESET}\n"
+	@printf "No relink:" && make -C ../../pipex bonus | grep -q "Nothing to be done for 'bonus'" && printf "${GREEN}${BOLD} OK ${RESET}\n" || printf "${BG_RED}${BOLD} FAILED ${RESET}\n"
+	@mv ../../pipex/pipex ./pipex
+	@printf "\n\n${SUBTITLE}Tests${RESET}"
 	@$(call RUNTEST,"B1.Three commands","input" "cat" "grep pipex" "wc -l" "output")
 	@$(call RUNTEST,"B2.Four commands","input" "cat" "tr a-z A-Z" "sort" "uniq" "output")
 	@$(call RUNTEST,"B3.Command not found in chain","input" "cat" "doesnotexist" "wc -l" "output")
 	@$(call RUNTEST,"B4.Large chain","input" "cat" "grep pipex" "grep hello" "wc -c" "sort" "uniq" "wc -l" "output")
+	@$(call RUNTEST,"B5.Here_doc basic","here_doc" "END" "cat" "wc -l" "output_hd",hello\nworld\npipex\nEND\n)
+	@$(call RUNTEST,"B6.Here_doc print input","here_doc" "END" "cat" "wc -l" "output_hd",hello\nworld\npipex\nEND\n)
+	@$(call RUNTEST,"B6.Here_doc empty input","here_doc" "END" "cat" "wc -c" "output_hd",END\n)
+	@$(call RUNTEST,"B7.Here_doc multiple cmds","here_doc" "FINISH" "tr a-z A-Z" "grep PIPEX" "wc -l" "output_hd",foo\npipex\nbar\nFINISH\n)
+	@$(call RUNTEST,"B8.Here_doc invalid command","here_doc" "END" "cat" "doesnotexist" "wc -c" "output_hd",hello\nworld\npipex\nEND\n)
+	@make -C ../../pipex -s fclean
 	@make clean_tests
